### ISSUE TITLE
Page overflows in a weird way

### ISSUE THREAD

**Issue by ngscheurich** [LouisianaGroups/louisiana-groups#18]
![louisiana_groups](https://user-images.githubusercontent.com/423798/38156635-19a2b9c2-3445-11e8-86fa-39f1cdcff8b5.png)

A cursory glance at devtools reveals that this might be being caused by the `margin` rules applied to the `.row` selector (the `.row` in the footer, specifically) but it may bear further investigation.

**Comment by adamculpepper** [comment]
@ngscheurich yea, I noticed that too and came to the same conclusion. I couldn't find a quick fix, so I moved on to more pressing things. I'll come back around to this, unless someone else wants to tackle it first.

**Comment by adamculpepper** [comment]
@ngscheurich thoughts on commit fix?
