### ISSUE TITLE
CNAME file?

### ISSUE THREAD

**Issue by ngscheurich** [LouisianaGroups/louisiana-groups#20]
I don't think we need this anymore since we're deploying with Netlify now. @adamculpepper?

**Comment by adamculpepper** [comment]
@ngscheurich yea, github added that in when I changed the setting to make it host. I'll try updating the setting and maybe it'll take care of it.

**Comment by adamculpepper** [comment]
Yep, that did it. I removed the A record from the domain as well, just leaving the CNAME for netlify
