### ISSUE TITLE
Add content loader

### ISSUE THREAD

**Issue by adamculpepper** [LouisianaGroups/louisiana-groups#23]
We need an animation or something for when the content is being loaded in.

**Comment by adamculpepper** [comment]
...any ideas how I can simulate loading time? I'm getting instant load times on local.

**Comment by ngscheurich** [comment]
@adamculpepper Check it:

![louisiana_groups](https://user-images.githubusercontent.com/423798/38438314-c39ea620-399f-11e8-89b1-0adbc3d36e30.png)

**Comment by adamculpepper** [comment]
@ngscheurich I tried that last night - no worky.

**Comment by ngscheurich** [comment]
@adamculpepper Haha, shit dude. It works great for me. I'm now certain you've angered some long-forgotten restless god or something.

**Comment by adamculpepper** [comment]
@ngscheurich well, no, I'm talking about I'm running the site on local, on my desktop. I see the data *immediately*. There isn't any time between refreshes on local, so I can't test adding in that loader.

**Comment by adamculpepper** [comment]
Hmm... it looks to be working tonight. Assuming it continues to work this weekend I should be able to knock out a loader.

Yea, totally unrelated... that hot-loading thing not happening. I thought that was just my setup and it could be fixed. 😭

**Comment by adamculpepper** [comment]
![image](https://user-images.githubusercontent.com/3942126/68251192-35b41280-ffe8-11e9-9239-6a44c31852fe.png)
Added in an animated content loader. This should do the trick.

**Comment by adamculpepper** [comment]
![image](https://user-images.githubusercontent.com/3942126/68251223-482e4c00-ffe8-11e9-8a2e-6cf0d010f32f.png)
Added in an animated content loader. This should do the trick.
