### ISSUE TITLE
Cache Static Content

### ISSUE THREAD

**Issue by adamculpepper** [LouisianaGroups/louisiana-groups#26]
@ngscheurich does Netflify allow you to set the header expiry limits on files?

I'm trying to get a better rating on the site here: http://www.webpagetest.org/result/180404_XZ_0f8a52104ce0a020fa820e05fa1edabb

![image](https://user-images.githubusercontent.com/3942126/38335893-9e7afa2c-3825-11e8-9c2f-ef61e439b7b5.png)

**Comment by ngscheurich** [comment]
@adamculpepper Good question. So, the short answer is "yes, but it isn't recommended." The long answer is here: https://www.netlify.com/blog/2017/02/23/better-living-through-caching/

Basically Netlify uses the multiplexing support in HTTP/2 to force browsers to check the freshness of assets on every request while keeping things super snappy. This will definitely look like a bad practice to many performance analysis tools, but in practice makes sense.

That all being said, Netlify does allow overriding their setting with your own caching headers if y'all want to go that way.

**Comment by adamculpepper** [comment]
Closing this since we're using github page instead of Netflify for the moment. Optimization is important to me, so I'll revisit all this again once we're further out of MVP development.
