### ISSUE TITLE
Cache'ing Static Content in general

### ISSUE THREAD

**Issue by adamculpepper** [LouisianaGroups/louisiana-groups#27]
Our static file caching needs a little love.

![image](https://user-images.githubusercontent.com/3942126/38336049-199a32ea-3826-11e8-9748-f2b7be03e38a.png)
source: http://www.webpagetest.org/performance_optimization.php?test=180404_XZ_0f8a52104ce0a020fa820e05fa1edabb&run=3#caching_step1

**Comment by ngscheurich** [comment]
* For the CSS, JS, and favicon files, see #26. Whatever decision we make there will apply.
* I'll look into adding a caching header to Pelican.
* We should host our own versions of the GitHub profile images so we can take advantage of Netlify’s caching.
* I believe our hands are tied on the Google stuff, but at least those are only warnings.

**Comment by ngscheurich** [comment]
Created https://github.com/LouisianaGroups/pelican/issues/6.

**Comment by adamculpepper** [comment]
Once we get a little further out of MVP development, I'll add a CDN to all the static assets.

**Comment by adamculpepper** [comment]
KeyCDN used and I set the expiry headers on the static assets to 1 month. The CDN should be linked to all files that are in our control (excluding Google Fonts, Analytics, etc.)
