### ISSUE TITLE
Contribution instructions

### ISSUE THREAD

**Issue by ngscheurich** [LouisianaGroups/louisiana-groups#3]
I wonder if requiring potential contributors to get in touch with someone on the project might be too high a barrier to entry. Perhaps we can just say that we‘re open to PRs? While we’re at it, we should add a contributor guidelines policy—I really like [Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html).

Perhaps we could change the *Development* section of the README to something like:

> ## Contributing
> Want to contribute? Awesome! We accept PRs—just be sure to follow the [contributor guidelines](https://github.com/adamculpepper/louisiana-groups/blob/master/CONTRIBUTING.md).

What does everyone else think?

**Comment by adamculpepper** [comment]
I love that idea! 👍

**Comment by ngscheurich** [comment]
Cool! This has been implemented in #9.
