### ISSUE TITLE
Access-Control-Allow-Origin issue

### ISSUE THREAD

**Issue by adamculpepper** [LouisianaGroups/louisiana-groups#31]
Fortunately/unfortunately I'm the only one that's apparently seeing this issue, but since we controls both ends of the site (domain and pelican), we should be able to fix this issue.

![image](https://user-images.githubusercontent.com/3942126/38403606-577ff6d0-392a-11e8-826f-218b8050252a.png)

**Comment by ngscheurich** [comment]
@adamculpepper Hmm… I'm really curious about what could be going on here. Currently, Pelican has a wide-open CORS policy (`access-control-allow-origin: *`). What are you seeing as the value of the `access-control-allow-origin` header when you receive that error?

**Comment by adamculpepper** [comment]
@ngscheurich I'm not familiar with Safari, how do I find that?

**Comment by ngscheurich** [comment]
@adamculpepper Ha, I'm glad you were able to brave the labyrinth and come out unscathed! When you get a chance, can you execute the following in the JavaScript console (in the devtools instance attached to your phone)?

```js
fetch("https://pelican.freighter.cloud/graphql", {
  body: '{"query":"{\n  groups {\n    name\n    }\n}\n"}',
  headers: { "content-type": "application/json" },
  method: "POST"
})
.then(response => console.log(response.status));
```

For reference, here's what I get:

<img width="568" alt="louisiana_groups" src="https://user-images.githubusercontent.com/423798/38405189-4324677a-3934-11e8-99d7-9d938a842ac7.png">

**Comment by adamculpepper** [comment]
@ngscheurich `SyntaxError: Unexpected token '>'`

![image](https://user-images.githubusercontent.com/3942126/38405326-e97d8cdc-3934-11e8-930f-85ffe1835f9f.png)

**Comment by james-alt** [comment]
So do you guys remember the other night when we discovered @adamculpepper doesn't believe in upgrading his phones and is on something like iOS 9? Yeah, that's probably the issue because iOS updates are the only time they push out Safari updates.

Fun fact, Apple does not allow other companies to make browsers for iOS. So when you grab Firefox or Chrome, the app you are downloading is just to give you the other nice perks of their ecosystems, like sync'd bookmarks, but the actual renderer is Safari.

**Comment by ngscheurich** [comment]
Hey, @adamculpepper—can you check your iOS Safari user agent string with something like:

```js
console.log(navigator.userAgent);
```

For reference, on my iPad I get `Mozilla/5.0 (iPad; CPU OS 11_1 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/11.0 Mobile/15B93 Safari/604.1`.

**Comment by adamculpepper** [comment]
@ngscheurich `undefined` Go fish!

**Comment by adamculpepper** [comment]
@ngscheurich navigator.appVersion worked

`5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13F69 Safari/601.1`

**Comment by adamculpepper** [comment]
Technology pivot fixed this issue.
