### ISSUE TITLE
Groups to add

### ISSUE THREAD

**Issue by jbnv** [LouisianaGroups/louisiana-groups#34]
Not sure if this is the best way to submit information--I figure better to do it this way and let you all decide how to add it to the page.

Acadiana Software Group
Lafayette
Every 2nd Wednesday (same as BRDNUG/BRSSUG) 6:30pm.
Facebook: https://www.facebook.com/groups/acadianasoftwaregroup/

gnocode
New Orleans
3rd Tuesday 7pm
gnocode.com

**Comment by james-alt** [comment]
Thanks @jbnv I'll go ahead and add them to the dataset.

**Comment by james-alt** [comment]
Looks like the [gnocode](gnocode.com) website isn't loading right now but I've found their [meetup page](https://www.meetup.com/gnocode/) and that seems to be active so I'm going to enter the data linking to that page with their next event.

**Comment by james-alt** [comment]
Both groups have been added to the list, I'll close the issue once I see it refresh on the site.
