### ISSUE TITLE
Sort Groups by Last Event

### ISSUE THREAD

**Issue by james-alt** [LouisianaGroups/louisiana-groups#35]
Currently the site is displaying Louisiana Game Developers first in the list even though the event has already passed. Need to update it to exclude past events in the sort. Based on the data, it should actually roll over to the next entry for that group which is in May.

**Comment by adamculpepper** [comment]
I have the array built that can be used to trigger the sort, but I'm having trouble merging the arrays back together now. I've tried ES6 `Object.assign()` and jQuery `$.extend` but neither are merging together `arrayEventGroupIDs` or `arrayGroups`. The `.then()` below (in the promise) works flawlessly. I'm just not seeing why this merge doesn't merge in too.

@ngscheurich can you take a look at this one in the `mvp` branch?

**Comment by ngscheurich** [comment]
@adamculpepper I'll have a look-see!

**Comment by adamculpepper** [comment]
Added in. Thanks for the suggestion @james-alt!
